name: github_action_auto_pr
on:
  push:
    branches: [ "acc_prod_backup" ]
jobs:
  createPullRequest:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4.0.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: ACC Prod Backup ${{ steps.date.outputs.date }}
          body: Auto-created Pull Request
          branch: ${{ github.ref }}
          base: main
          reviewers: oopstavo
